/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Move mouse cursor to absolute screen position */
export declare function moveMouse(x: number, y: number): void
/**
 * Simulate mouse button press/release
 * button: 0=left, 1=right, 2=middle
 */
export declare function mouseButton(button: number, down: boolean, x: number, y: number): void
/** Simulate mouse wheel scroll */
export declare function mouseScroll(deltaX: number, deltaY: number, x: number, y: number): void
/** Simulate key press */
export declare function keyDown(vkCode: number): void
/** Simulate key release */
export declare function keyUp(vkCode: number): void
/** Type text using clipboard paste method */
export declare function typeText(text: string): void
