/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Move mouse cursor to absolute screen position */
export declare function moveMouse(x: number, y: number): void
/**
 * Simulate mouse button press/release
 * button: 0=left, 1=right, 2=middle
 */
export declare function mouseButton(button: number, down: boolean, x: number, y: number): void
/** Simulate mouse wheel scroll */
export declare function mouseScroll(deltaX: number, deltaY: number, x: number, y: number): void
/** Simulate key press */
export declare function keyDown(vkCode: number): void
/** Simulate key release */
export declare function keyUp(vkCode: number): void
/** Type text using clipboard paste method */
export declare function typeText(text: string): void
/** Bring a captured application window to the foreground before injecting input. */
export declare function focusWindow(windowId: string): void
/**
 * macOS TIS API を使って現在の IME 入力ソースを取得する。
 *
 * 返り値:
 * - `"japanese"` : 日本語入力ソースがアクティブ
 *   (英数キー・かなキー・Ctrl+Space・Globe キー・メニューバーボタン等の
 *   あらゆる切り替え方法に対応)
 * - `"latin"` : ASCII / ラテン文字入力ソースがアクティブ
 *
 * macOS 以外では常に `"latin"` を返す。
 */
export declare function getCurrentImeMode(): string
/**
 * Windows IMM32 API (ImmSetOpenStatus) を使って IME を直接 ON/OFF する。
 * `open=true` で日本語入力 ON、`open=false` で英数入力 (IME OFF)。
 * フォアグラウンドウィンドウの IME コンテキストに対して動作する。
 * Windows 以外では何もしない。
 */
export declare function setImeMode(open: boolean): void
/** Windows IMM32 API を使って、指定ウィンドウの IME を直接 ON/OFF する。 */
export declare function setImeModeForWindow(windowId: string, open: boolean): void
export declare const DOM_KEY_TO_VK: Record<string, number>
export declare const DOM_KEY_TO_MAC_KEYCODE: Record<string, number>
